spring:
  datasource:
    url: jdbc:mysql://localhost/ecommerce_sports?serverTimezone=UTC
    username: root 
    password: ser.23
    #initialization-mode: always #never
  jpa:
    show-sql: false #true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
server:
  port : 9090