<<<<<<< Updated upstream
spring:
  datasource:
    url: jdbc:mysql://localhost/ecommerce_sports?serverTimezone=UTC
    username: root 
    password: 2771999
    #initialization-mode: always #never
  jpa:
    show-sql: false #true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
    mode: HTML5
    
  mail:
    host : smtp.gmail.com
    port: 587
    username: proyectodesoftwaretp@gmail.com
    password: 2771999tpps
    properties:      mail:
        smtp:
          starttls :
            enable : true
          auth : true
         
server:
=======
spring:
  datasource:
    url: jdbc:mysql://localhost/ecommerce_sports?serverTimezone=UTC
    username: root 
    password: toor
    initialization-mode: always #never
  jpa:
    show-sql: false #true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
    mode: HTML5
    
  mail:
    host : smtp.gmail.com
    port: 587
    username: proyectodesoftwaretp@gmail.com
    password: 2771999tpps
    properties:
      mail:
        smtp:
          starttls :
            enable : true
          auth : true
         
server:
>>>>>>> Stashed changes
  port : 9090